#!/bin/bash
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-

opts=$(getopt -q -o "" --longoptions "runtime:" -n "getopt.sh" -- "$@");
eval set -- "$opts";
while true; do
    case "$1" in
        --runtime)
            shift
            val="$1"
            if echo "${val}" | grep -q 'h$'; then
                val=$(( ${val%h} * 3600 ))
            elif echo "${val}" | grep -q 'm$'; then
                val=$(( ${val%m} * 60 ))
            else
                val="${val%s}"
            fi
            echo "${val}"
            shift
            ;;
        --)
            shift
            exit
            ;;
        *)
            shift
            ;;
    esac
done
